services:
  web:
    build:
      context: ./gpds-ui/
      dockerfile: Dockerfile
    ports:
      - "8081:81" # Exponer el puerto 81 del contenedor en el puerto 8081 de tu host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Solo si tienes un archivo nginx.conf personaliza
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
